--------------------------------------------------------
--  File created - Friday-December-15-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PUBLISHER
--------------------------------------------------------

  CREATE TABLE "HR"."PUBLISHER" 
   (	"PUB_ID" VARCHAR2(20 BYTE), 
	"PUB_NAME" VARCHAR2(30 BYTE), 
	"RATING" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into HR.PUBLISHER
SET DEFINE OFF;
Insert into HR.PUBLISHER (PUB_ID,PUB_NAME,RATING) values ('7000','GKHYR PUBLISHERS','D');
Insert into HR.PUBLISHER (PUB_ID,PUB_NAME,RATING) values ('7001','MUPEI PUBLISHERS','A');
Insert into HR.PUBLISHER (PUB_ID,PUB_NAME,RATING) values ('7002','FPRXU PUBLISHERS','C');
Insert into HR.PUBLISHER (PUB_ID,PUB_NAME,RATING) values ('7003','GWEIP PUBLISHERS','E');
Insert into HR.PUBLISHER (PUB_ID,PUB_NAME,RATING) values ('7004','PNGXE PUBLISHERS','A');
Insert into HR.PUBLISHER (PUB_ID,PUB_NAME,RATING) values ('7005','DHOIY PUBLISHERS','E');
Insert into HR.PUBLISHER (PUB_ID,PUB_NAME,RATING) values ('7006','RJXXF PUBLISHERS','D');
Insert into HR.PUBLISHER (PUB_ID,PUB_NAME,RATING) values ('7007','BESSW PUBLISHERS','B');
Insert into HR.PUBLISHER (PUB_ID,PUB_NAME,RATING) values ('7008','GPXOH PUBLISHERS','A');
Insert into HR.PUBLISHER (PUB_ID,PUB_NAME,RATING) values ('7009','WXXOX PUBLISHERS','B');
Insert into HR.PUBLISHER (PUB_ID,PUB_NAME,RATING) values ('7010','IPMHN PUBLISHERS','C');
Insert into HR.PUBLISHER (PUB_ID,PUB_NAME,RATING) values ('7011','SZXEG PUBLISHERS','D');
Insert into HR.PUBLISHER (PUB_ID,PUB_NAME,RATING) values ('7012','EACOK PUBLISHERS','E');
Insert into HR.PUBLISHER (PUB_ID,PUB_NAME,RATING) values ('7013','SLAZT PUBLISHERS','B');
Insert into HR.PUBLISHER (PUB_ID,PUB_NAME,RATING) values ('7014','JUOJG PUBLISHERS','B');
Insert into HR.PUBLISHER (PUB_ID,PUB_NAME,RATING) values ('7015','RASTG PUBLISHERS','A');
Insert into HR.PUBLISHER (PUB_ID,PUB_NAME,RATING) values ('7016','JEOCC PUBLISHERS','E');
Insert into HR.PUBLISHER (PUB_ID,PUB_NAME,RATING) values ('7017','DEZBT PUBLISHERS','D');
Insert into HR.PUBLISHER (PUB_ID,PUB_NAME,RATING) values ('7018','HCONW PUBLISHERS','E');
Insert into HR.PUBLISHER (PUB_ID,PUB_NAME,RATING) values ('7019','XSMTR PUBLISHERS','A');
Insert into HR.PUBLISHER (PUB_ID,PUB_NAME,RATING) values ('7020','QPUFQ PUBLISHERS','D');
Insert into HR.PUBLISHER (PUB_ID,PUB_NAME,RATING) values ('7021','JMMDH PUBLISHERS','D');
Insert into HR.PUBLISHER (PUB_ID,PUB_NAME,RATING) values ('7022','UCNXM PUBLISHERS','E');
Insert into HR.PUBLISHER (PUB_ID,PUB_NAME,RATING) values ('7023','OHQWJ PUBLISHERS','A');
Insert into HR.PUBLISHER (PUB_ID,PUB_NAME,RATING) values ('7024','FUNIA PUBLISHERS','E');
Insert into HR.PUBLISHER (PUB_ID,PUB_NAME,RATING) values ('7025','ECEPN PUBLISHERS','B');
Insert into HR.PUBLISHER (PUB_ID,PUB_NAME,RATING) values ('7026','HUBLP PUBLISHERS','B');
Insert into HR.PUBLISHER (PUB_ID,PUB_NAME,RATING) values ('7027','UOGPY PUBLISHERS','D');
Insert into HR.PUBLISHER (PUB_ID,PUB_NAME,RATING) values ('7028','GBPOA PUBLISHERS','C');
Insert into HR.PUBLISHER (PUB_ID,PUB_NAME,RATING) values ('7029','QRROI PUBLISHERS','E');
Insert into HR.PUBLISHER (PUB_ID,PUB_NAME,RATING) values ('7030','MPNUP PUBLISHERS','D');
Insert into HR.PUBLISHER (PUB_ID,PUB_NAME,RATING) values ('7031','GXUXH PUBLISHERS','D');
Insert into HR.PUBLISHER (PUB_ID,PUB_NAME,RATING) values ('7032','TLIFL PUBLISHERS','B');
Insert into HR.PUBLISHER (PUB_ID,PUB_NAME,RATING) values ('7033','RBTBR PUBLISHERS','A');
Insert into HR.PUBLISHER (PUB_ID,PUB_NAME,RATING) values ('7034','FBLJL PUBLISHERS','C');
Insert into HR.PUBLISHER (PUB_ID,PUB_NAME,RATING) values ('7035','UDSGK PUBLISHERS','B');
Insert into HR.PUBLISHER (PUB_ID,PUB_NAME,RATING) values ('7036','BSNCM PUBLISHERS','E');
Insert into HR.PUBLISHER (PUB_ID,PUB_NAME,RATING) values ('7037','TTRLL PUBLISHERS','D');
Insert into HR.PUBLISHER (PUB_ID,PUB_NAME,RATING) values ('7038','ZTJSK PUBLISHERS','A');
Insert into HR.PUBLISHER (PUB_ID,PUB_NAME,RATING) values ('7039','CJHKA PUBLISHERS','E');
Insert into HR.PUBLISHER (PUB_ID,PUB_NAME,RATING) values ('7040','LFTBK PUBLISHERS','D');
Insert into HR.PUBLISHER (PUB_ID,PUB_NAME,RATING) values ('7041','NGBCA PUBLISHERS','B');
Insert into HR.PUBLISHER (PUB_ID,PUB_NAME,RATING) values ('7042','OMCFQ PUBLISHERS','C');
Insert into HR.PUBLISHER (PUB_ID,PUB_NAME,RATING) values ('7043','KCTMA PUBLISHERS','C');
Insert into HR.PUBLISHER (PUB_ID,PUB_NAME,RATING) values ('7044','ZSLFG PUBLISHERS','C');
Insert into HR.PUBLISHER (PUB_ID,PUB_NAME,RATING) values ('7045','KQDJY PUBLISHERS','B');
Insert into HR.PUBLISHER (PUB_ID,PUB_NAME,RATING) values ('7046','YWYEB PUBLISHERS','A');
Insert into HR.PUBLISHER (PUB_ID,PUB_NAME,RATING) values ('7047','DUTPL PUBLISHERS','B');
Insert into HR.PUBLISHER (PUB_ID,PUB_NAME,RATING) values ('7048','ALBLL PUBLISHERS','E');
Insert into HR.PUBLISHER (PUB_ID,PUB_NAME,RATING) values ('7049','KRDKM PUBLISHERS','A');
Insert into HR.PUBLISHER (PUB_ID,PUB_NAME,RATING) values ('7050','OISLN PUBLISHERS','A');
Insert into HR.PUBLISHER (PUB_ID,PUB_NAME,RATING) values ('7051','MEGFY PUBLISHERS','B');
Insert into HR.PUBLISHER (PUB_ID,PUB_NAME,RATING) values ('7052','XWEYL PUBLISHERS','E');
Insert into HR.PUBLISHER (PUB_ID,PUB_NAME,RATING) values ('7053','RQDIP PUBLISHERS','A');
Insert into HR.PUBLISHER (PUB_ID,PUB_NAME,RATING) values ('7054','HDERA PUBLISHERS','C');
Insert into HR.PUBLISHER (PUB_ID,PUB_NAME,RATING) values ('7055','FWTJL PUBLISHERS','D');
Insert into HR.PUBLISHER (PUB_ID,PUB_NAME,RATING) values ('7056','PQSGN PUBLISHERS','D');
Insert into HR.PUBLISHER (PUB_ID,PUB_NAME,RATING) values ('7057','FFIPF PUBLISHERS','A');
Insert into HR.PUBLISHER (PUB_ID,PUB_NAME,RATING) values ('7058','YEUZZ PUBLISHERS','E');
Insert into HR.PUBLISHER (PUB_ID,PUB_NAME,RATING) values ('7059','EHMLY PUBLISHERS','B');
Insert into HR.PUBLISHER (PUB_ID,PUB_NAME,RATING) values ('7060','MQFEH PUBLISHERS','C');
Insert into HR.PUBLISHER (PUB_ID,PUB_NAME,RATING) values ('7061','KLEQC PUBLISHERS','C');
Insert into HR.PUBLISHER (PUB_ID,PUB_NAME,RATING) values ('7062','ZUFXB PUBLISHERS','A');
Insert into HR.PUBLISHER (PUB_ID,PUB_NAME,RATING) values ('7063','ZUMGU PUBLISHERS','B');
Insert into HR.PUBLISHER (PUB_ID,PUB_NAME,RATING) values ('7064','UPRQI PUBLISHERS','D');
Insert into HR.PUBLISHER (PUB_ID,PUB_NAME,RATING) values ('7065','TNRCK PUBLISHERS','B');
Insert into HR.PUBLISHER (PUB_ID,PUB_NAME,RATING) values ('7066','DBGHT PUBLISHERS','C');
Insert into HR.PUBLISHER (PUB_ID,PUB_NAME,RATING) values ('7067','TIUNA PUBLISHERS','C');
Insert into HR.PUBLISHER (PUB_ID,PUB_NAME,RATING) values ('7068','LICOA PUBLISHERS','C');
Insert into HR.PUBLISHER (PUB_ID,PUB_NAME,RATING) values ('7069','QZHFO PUBLISHERS','A');
Insert into HR.PUBLISHER (PUB_ID,PUB_NAME,RATING) values ('7070','CDFLF PUBLISHERS','C');
Insert into HR.PUBLISHER (PUB_ID,PUB_NAME,RATING) values ('7071','SMTKF PUBLISHERS','E');
Insert into HR.PUBLISHER (PUB_ID,PUB_NAME,RATING) values ('7072','OHEAZ PUBLISHERS','B');
Insert into HR.PUBLISHER (PUB_ID,PUB_NAME,RATING) values ('7073','WEIHO PUBLISHERS','A');
Insert into HR.PUBLISHER (PUB_ID,PUB_NAME,RATING) values ('7074','FOSNN PUBLISHERS','A');
Insert into HR.PUBLISHER (PUB_ID,PUB_NAME,RATING) values ('7075','XIYTS PUBLISHERS','B');
Insert into HR.PUBLISHER (PUB_ID,PUB_NAME,RATING) values ('7076','GUZPY PUBLISHERS','B');
Insert into HR.PUBLISHER (PUB_ID,PUB_NAME,RATING) values ('7077','GPZEZ PUBLISHERS','D');
Insert into HR.PUBLISHER (PUB_ID,PUB_NAME,RATING) values ('7078','ZEJAU PUBLISHERS','C');
Insert into HR.PUBLISHER (PUB_ID,PUB_NAME,RATING) values ('7079','QIIRF PUBLISHERS','A');
Insert into HR.PUBLISHER (PUB_ID,PUB_NAME,RATING) values ('7080','FURCE PUBLISHERS','B');
Insert into HR.PUBLISHER (PUB_ID,PUB_NAME,RATING) values ('7081','KMKMI PUBLISHERS','D');
Insert into HR.PUBLISHER (PUB_ID,PUB_NAME,RATING) values ('7082','XSKEO PUBLISHERS','A');
Insert into HR.PUBLISHER (PUB_ID,PUB_NAME,RATING) values ('7083','MIQTB PUBLISHERS','C');
Insert into HR.PUBLISHER (PUB_ID,PUB_NAME,RATING) values ('7084','HTAOJ PUBLISHERS','B');
Insert into HR.PUBLISHER (PUB_ID,PUB_NAME,RATING) values ('7085','JYDFX PUBLISHERS','C');
Insert into HR.PUBLISHER (PUB_ID,PUB_NAME,RATING) values ('7086','ACDIM PUBLISHERS','A');
Insert into HR.PUBLISHER (PUB_ID,PUB_NAME,RATING) values ('7087','PIKPI PUBLISHERS','D');
Insert into HR.PUBLISHER (PUB_ID,PUB_NAME,RATING) values ('7088','KPEYE PUBLISHERS','E');
Insert into HR.PUBLISHER (PUB_ID,PUB_NAME,RATING) values ('7089','FQXYK PUBLISHERS','C');
Insert into HR.PUBLISHER (PUB_ID,PUB_NAME,RATING) values ('7090','NZAJB PUBLISHERS','E');
Insert into HR.PUBLISHER (PUB_ID,PUB_NAME,RATING) values ('7091','ROBFI PUBLISHERS','B');
Insert into HR.PUBLISHER (PUB_ID,PUB_NAME,RATING) values ('7092','XODKS PUBLISHERS','B');
Insert into HR.PUBLISHER (PUB_ID,PUB_NAME,RATING) values ('7093','TZDJO PUBLISHERS','B');
Insert into HR.PUBLISHER (PUB_ID,PUB_NAME,RATING) values ('7094','RYWDF PUBLISHERS','A');
Insert into HR.PUBLISHER (PUB_ID,PUB_NAME,RATING) values ('7095','HDDJC PUBLISHERS','B');
Insert into HR.PUBLISHER (PUB_ID,PUB_NAME,RATING) values ('7096','IFUUR PUBLISHERS','A');
Insert into HR.PUBLISHER (PUB_ID,PUB_NAME,RATING) values ('7097','FRWRT PUBLISHERS','C');
Insert into HR.PUBLISHER (PUB_ID,PUB_NAME,RATING) values ('7098','CEYUY PUBLISHERS','A');
Insert into HR.PUBLISHER (PUB_ID,PUB_NAME,RATING) values ('7099','WGLAH PUBLISHERS','A');
--------------------------------------------------------
--  DDL for Index SYS_C0012911
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."SYS_C0012911" ON "HR"."PUBLISHER" ("PUB_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table PUBLISHER
--------------------------------------------------------

  ALTER TABLE "HR"."PUBLISHER" ADD PRIMARY KEY ("PUB_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
